name: Unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install elm
        run: |
          curl -L -o elm.gz https://github.com/elm/compiler/releases/download/0.19.1/binary-for-linux-64-bit.gz
          gunzip elm.gz
          chmod +x elm
          sudo mv elm /usr/local/bin/
          
      - name: Run elm-test
        run: npx elm-test

      - name: Run elm-verify-examples
        run: npx -p elm-test -p elm-verify-examples -c 'elm-verify-examples --run-tests'
